name: secret-notes

services:
  db:
    image: valkey/valkey:9-alpine
    command: valkey-server --save 60 1 --loglevel warning
    mem_limit: 1g
    ports:
      - '127.0.0.1:8081:6379'
    volumes:
      - db_data:/data

volumes:
  db_data: